"""
Report generator — produces management-ready Markdown and PDF reports.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.config import settings
from app.llm.schemas import RCAOutput
from app.memory.chromadb_store import SimilarIncident

logger = logging.getLogger(__name__)

SEVERITY_EMOJI = {"low": "🟢", "medium": "🟡", "high": "🟠", "critical": "🔴"}
SEVERITY_LABEL = {"low": "LOW", "medium": "MEDIUM", "high": "HIGH", "critical": "CRITICAL"}


class ReportGenerator:
    def __init__(self) -> None:
        self.output_dir = settings.reports.output_path
        self.company = settings.reports.company_name

    # ──────────────────────────────────────────────────────────────
    # Markdown
    # ──────────────────────────────────────────────────────────────

    def generate_markdown(
        self,
        incident_id: str,
        rca: RCAOutput,
        namespace: str,
        similar_incidents: list[SimilarIncident] | None = None,
    ) -> Path:
        ts_file = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        ts_human = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
        filename = f"RCA_{incident_id[:8]}_{ts_file}.md"
        path = self.output_dir / filename

        sev_icon = SEVERITY_EMOJI.get(rca.severity, "⚪")
        sev_label = SEVERITY_LABEL.get(rca.severity, rca.severity.upper())
        confidence_pct = f"{rca.confidence_score:.0%}"
        short_id = incident_id[:8].upper()

        lines: list[str] = []

        # ── Cover ────────────────────────────────────────────────
        lines += [
            f"# {sev_icon} Root Cause Analysis Report",
            f"### Incident `{short_id}` — {namespace}",
            f"",
            f"| Field | Value |",
            f"|---|---|",
            f"| **Organisation** | {self.company} |",
            f"| **Report Date** | {ts_human} |",
            f"| **Incident ID** | `{incident_id}` |",
            f"| **Namespace** | `{namespace}` |",
            f"| **Issue Type** | `{rca.issue_type}` |",
            f"| **Severity** | {sev_icon} **{sev_label}** |",
            f"| **AI Confidence** | {confidence_pct} |",
            f"| **Generated By** | {self.company} AI RCA Agent (Ollama) |",
            f"",
            f"---",
            f"",
        ]

        # ── 1. Executive Summary ─────────────────────────────────
        lines += [
            f"## 1. Executive Summary",
            f"",
            f"> {rca.executive_summary}",
            f"",
            f"---",
            f"",
        ]

        # ── 2. Incident Overview ─────────────────────────────────
        lines += [
            f"## 2. Incident Overview",
            f"",
            f"| Attribute | Detail |",
            f"|---|---|",
            f"| **Affected Component** | `{namespace}` namespace |",
            f"| **Issue Classification** | {rca.issue_type} |",
            f"| **Business Impact** | {rca.impact_assessment or 'Under assessment'} |",
            f"| **Severity Level** | {sev_icon} {sev_label} |",
            f"| **Detection Method** | AI-powered automated monitoring |",
            f"",
            f"---",
            f"",
        ]

        # ── 3. Root Cause Analysis ──────────────────────────────
        lines += [
            f"## 3. Root Cause Analysis",
            f"",
            f"### 3.1 Primary Root Cause",
            f"",
            f"{rca.root_cause}",
            f"",
            f"### 3.2 Contributing Factors",
            f"",
            f"{rca.contributing_factors or '_None identified._'}",
            f"",
            f"### 3.3 Evidence Summary",
            f"",
            f"{rca.evidence_summary or '_No evidence summary available._'}",
            f"",
            f"---",
            f"",
        ]

        # ── 4. Impact Assessment ────────────────────────────────
        lines += [
            f"## 4. Impact Assessment",
            f"",
            f"{rca.impact_assessment or '_Impact assessment pending._'}",
            f"",
            f"---",
            f"",
        ]

        # ── 5. Remediation Plan ─────────────────────────────────
        lines += [
            f"## 5. Remediation Plan",
            f"",
            f"### 5.1 Immediate Actions (Fix)",
            f"",
            f"{rca.recommended_fix}",
            f"",
            f"### 5.2 Validation & Verification",
            f"",
            f"{rca.validation_steps or '_No validation steps provided._'}",
            f"",
            f"---",
            f"",
        ]

        # ── 6. Preventive Measures ──────────────────────────────
        lines += [
            f"## 6. Preventive Measures",
            f"",
            f"{rca.preventive_actions or '_No preventive actions provided._'}",
            f"",
            f"---",
            f"",
        ]

        # ── 7. Similar Past Incidents ───────────────────────────
        if similar_incidents:
            lines += [
                f"## 7. Similar Past Incidents",
                f"",
                f"The following historical incidents were identified as relevant:",
                f"",
                f"| Similarity | Incident Title | Issue Type | Root Cause |",
                f"|---|---|---|---|",
            ]
            for s in similar_incidents[:5]:
                rc_short = (s.root_cause[:60] + "…") if len(s.root_cause) > 60 else s.root_cause
                lines.append(f"| {s.similarity:.0%} | {s.title} | {s.issue_type} | {rc_short} |")
            lines += [f"", f"---", f""]

        # ── 8. Action Items ─────────────────────────────────────
        lines += [
            f"## 8. Action Items & Owners",
            f"",
            f"| # | Action | Priority | Owner | Status |",
            f"|---|---|---|---|---|",
            f"| 1 | Apply immediate fix (see Section 5.1) | 🔴 Immediate | On-Call SRE | Open |",
            f"| 2 | Validate fix using steps in Section 5.2 | 🔴 Immediate | On-Call SRE | Open |",
            f"| 3 | Implement preventive measures (Section 6) | 🟡 Short-term | Platform Team | Open |",
            f"| 4 | Update runbook with findings | 🟢 Long-term | SRE Lead | Open |",
            f"| 5 | Schedule post-incident review | 🟢 Long-term | Engineering Manager | Open |",
            f"",
            f"---",
            f"",
        ]

        # ── 9. Sign-off ─────────────────────────────────────────
        lines += [
            f"## 9. Report Sign-off",
            f"",
            f"| Role | Name | Signature | Date |",
            f"|---|---|---|---|",
            f"| On-Call Engineer | | | |",
            f"| SRE Lead | | | |",
            f"| Engineering Manager | | | |",
            f"",
            f"---",
            f"",
            f"*This report was automatically generated by the **{self.company} AI RCA Agent**",
            f"powered by Ollama (offline AI). AI confidence: {confidence_pct}.",
            f"All findings and recommendations must be reviewed by a qualified engineer",
            f"before implementation.*",
            f"",
            f"---",
            f"*Incident ID: `{incident_id}` | Generated: {ts_human}*",
        ]

        path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Markdown report written: %s", path)
        return path

    # ──────────────────────────────────────────────────────────────
    # PDF
    # ──────────────────────────────────────────────────────────────

    def generate_pdf(
        self,
        incident_id: str,
        rca: RCAOutput,
        namespace: str,
    ) -> Path:
        ts_file = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        ts_human = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
        filename = f"RCA_{incident_id[:8]}_{ts_file}.pdf"
        path = self.output_dir / filename
        short_id = incident_id[:8].upper()

        try:
            from reportlab.lib import colors
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
            from reportlab.lib.units import cm
            from reportlab.platypus import (
                HRFlowable, PageBreak, Paragraph, SimpleDocTemplate,
                Spacer, Table, TableStyle,
            )

            W, H = A4

            SEV_COLORS = {
                "low":      colors.HexColor("#16a34a"),
                "medium":   colors.HexColor("#ca8a04"),
                "high":     colors.HexColor("#ea580c"),
                "critical": colors.HexColor("#dc2626"),
            }
            BRAND  = colors.HexColor("#1e293b")
            ACCENT = colors.HexColor("#6366f1")
            LIGHT  = colors.HexColor("#f8fafc")
            MUTED  = colors.HexColor("#64748b")
            sev_color = SEV_COLORS.get(rca.severity, colors.grey)
            sev_label = SEVERITY_LABEL.get(rca.severity, rca.severity.upper())

            styles = getSampleStyleSheet()

            def S(name, **kw):
                return ParagraphStyle(name, parent=styles["Normal"], **kw)

            cover_title = S("CoverTitle", fontSize=26, textColor=colors.white,
                            fontName="Helvetica-Bold", spaceAfter=4, leading=30)
            cover_sub   = S("CoverSub",   fontSize=13, textColor=colors.HexColor("#cbd5e1"),
                            fontName="Helvetica", spaceAfter=2)
            h1 = S("H1", fontSize=14, fontName="Helvetica-Bold", textColor=BRAND,
                   spaceBefore=14, spaceAfter=6, borderPad=4)
            h2 = S("H2", fontSize=11, fontName="Helvetica-Bold", textColor=ACCENT,
                   spaceBefore=10, spaceAfter=4)
            body = S("Body", fontSize=9.5, leading=15, spaceAfter=5, textColor=BRAND)
            small = S("Small", fontSize=8, textColor=MUTED, leading=12)
            exec_style = S("Exec", fontSize=10, leading=16, spaceAfter=6,
                           textColor=BRAND, fontName="Helvetica-Oblique",
                           leftIndent=12, rightIndent=12, borderPad=8)

            story: list = []

            # ── Cover page ──────────────────────────────────────
            # Coloured banner
            banner = Table(
                [[Paragraph(f"ROOT CAUSE ANALYSIS REPORT", cover_title)],
                 [Paragraph(f"Incident {short_id} &nbsp;·&nbsp; {namespace}", cover_sub)],
                 [Paragraph(f"{ts_human}", cover_sub)]],
                colWidths=[W - 4*cm],
            )
            banner.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,-1), BRAND),
                ("TOPPADDING",    (0,0), (-1,-1), 16),
                ("BOTTOMPADDING", (0,0), (-1,-1), 16),
                ("LEFTPADDING",   (0,0), (-1,-1), 20),
                ("RIGHTPADDING",  (0,0), (-1,-1), 20),
            ]))
            story.append(banner)
            story.append(Spacer(1, 0.6*cm))

            # Severity badge
            badge = Table(
                [[Paragraph(f"⬤  SEVERITY: {sev_label}", S("Badge",
                    fontSize=13, fontName="Helvetica-Bold",
                    textColor=colors.white))]],
                colWidths=[W - 4*cm],
            )
            badge.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,-1), sev_color),
                ("TOPPADDING",    (0,0), (-1,-1), 10),
                ("BOTTOMPADDING", (0,0), (-1,-1), 10),
                ("LEFTPADDING",   (0,0), (-1,-1), 20),
            ]))
            story.append(badge)
            story.append(Spacer(1, 0.6*cm))

            # Metadata table
            meta_rows = [
                ["Organisation", self.company],
                ["Report Date",  ts_human],
                ["Incident ID",  incident_id],
                ["Namespace",    namespace],
                ["Issue Type",   rca.issue_type],
                ["Severity",     sev_label],
                ["AI Confidence", f"{rca.confidence_score:.0%}"],
                ["Generated By", f"{self.company} AI RCA Agent (Ollama)"],
            ]
            meta_table = Table(
                [[Paragraph(f"<b>{k}</b>", body), Paragraph(v, body)] for k, v in meta_rows],
                colWidths=[4.5*cm, W - 4*cm - 4.5*cm],
            )
            meta_table.setStyle(TableStyle([
                ("GRID",           (0,0), (-1,-1), 0.4, colors.HexColor("#e2e8f0")),
                ("BACKGROUND",     (0,0), (0,-1), colors.HexColor("#f1f5f9")),
                ("ROWBACKGROUNDS", (0,0), (-1,-1), [colors.white, LIGHT]),
                ("TOPPADDING",     (0,0), (-1,-1), 5),
                ("BOTTOMPADDING",  (0,0), (-1,-1), 5),
                ("LEFTPADDING",    (0,0), (-1,-1), 8),
                ("FONTSIZE",       (0,0), (-1,-1), 9),
                ("TEXTCOLOR",      (1,5), (1,5), sev_color),   # severity value
            ]))
            story.append(meta_table)
            story.append(PageBreak())

            # ── Section helper ──────────────────────────────────
            def section(title: str, content: str, *, highlight: bool = False) -> None:
                # Section header bar
                hdr = Table(
                    [[Paragraph(title, S("SHdr", fontSize=12, fontName="Helvetica-Bold",
                                        textColor=colors.white))]],
                    colWidths=[W - 4*cm],
                )
                hdr.setStyle(TableStyle([
                    ("BACKGROUND",    (0,0), (-1,-1), BRAND if not highlight else ACCENT),
                    ("TOPPADDING",    (0,0), (-1,-1), 7),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 7),
                    ("LEFTPADDING",   (0,0), (-1,-1), 10),
                ]))
                story.append(hdr)
                story.append(Spacer(1, 0.15*cm))

                if not content or content.strip() in ("_None identified._", "_Not assessed._",
                                                       "_No validation steps provided._",
                                                       "_No preventive actions provided._"):
                    story.append(Paragraph("Not provided.", S("NA", fontSize=9, textColor=MUTED)))
                else:
                    for line in content.split("\n"):
                        stripped = line.strip()
                        if not stripped:
                            continue
                        # Bullet-style lines
                        if stripped.startswith(("- ", "• ", "* ")):
                            stripped = "• " + stripped[2:]
                        elif stripped[0].isdigit() and stripped[1:3] in (". ", ") "):
                            stripped = f"  {stripped}"
                        style = exec_style if highlight else body
                        story.append(Paragraph(stripped, style))
                story.append(Spacer(1, 0.3*cm))

            # ── 1. Executive Summary ────────────────────────────
            section("1.  Executive Summary", rca.executive_summary, highlight=True)

            # ── 2. Root Cause ───────────────────────────────────
            section("2.  Root Cause", rca.root_cause)

            # ── 3. Contributing Factors ─────────────────────────
            section("3.  Contributing Factors", rca.contributing_factors or "None identified.")

            # ── 4. Impact Assessment ────────────────────────────
            section("4.  Impact Assessment", rca.impact_assessment or "Not assessed.")

            # ── 5. Evidence Summary ─────────────────────────────
            section("5.  Evidence Summary", rca.evidence_summary or "No evidence summary available.")

            # ── 6. Recommended Fix ──────────────────────────────
            section("6.  Recommended Fix", rca.recommended_fix)

            # ── 7. Validation Steps ─────────────────────────────
            section("7.  Validation Steps", rca.validation_steps or "Not provided.")

            # ── 8. Preventive Measures ──────────────────────────
            section("8.  Preventive Measures", rca.preventive_actions or "Not provided.")

            # ── 9. Action Items table ────────────────────────────
            hdr = Table(
                [[Paragraph("9.  Action Items & Owners", S("SHdr2", fontSize=12,
                             fontName="Helvetica-Bold", textColor=colors.white))]],
                colWidths=[W - 4*cm],
            )
            hdr.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,-1), BRAND),
                ("TOPPADDING",    (0,0), (-1,-1), 7),
                ("BOTTOMPADDING", (0,0), (-1,-1), 7),
                ("LEFTPADDING",   (0,0), (-1,-1), 10),
            ]))
            story.append(hdr)
            story.append(Spacer(1, 0.15*cm))

            action_hdr = [
                Paragraph("<b>#</b>", body),
                Paragraph("<b>Action</b>", body),
                Paragraph("<b>Priority</b>", body),
                Paragraph("<b>Owner</b>", body),
                Paragraph("<b>Status</b>", body),
            ]
            action_rows = [
                ["1", "Apply immediate fix (see Section 6)", "Immediate", "On-Call SRE", "Open"],
                ["2", "Validate fix using Section 7 steps",  "Immediate", "On-Call SRE", "Open"],
                ["3", "Implement preventive measures",        "Short-term","Platform Team","Open"],
                ["4", "Update runbook with findings",         "Long-term", "SRE Lead",    "Open"],
                ["5", "Schedule post-incident review",        "Long-term", "Eng. Manager","Open"],
            ]
            priority_colors = {
                "Immediate":  colors.HexColor("#fee2e2"),
                "Short-term": colors.HexColor("#fef9c3"),
                "Long-term":  colors.HexColor("#dcfce7"),
            }
            at_data = [action_hdr] + [
                [Paragraph(str(c), body) for c in row] for row in action_rows
            ]
            at = Table(at_data, colWidths=[0.6*cm, 6.5*cm, 2.5*cm, 3.2*cm, 2*cm])
            at_style = [
                ("BACKGROUND",    (0,0), (-1,0),  colors.HexColor("#1e293b")),
                ("TEXTCOLOR",     (0,0), (-1,0),  colors.white),
                ("FONTNAME",      (0,0), (-1,0),  "Helvetica-Bold"),
                ("FONTSIZE",      (0,0), (-1,-1), 8.5),
                ("GRID",          (0,0), (-1,-1), 0.4, colors.HexColor("#e2e8f0")),
                ("ROWBACKGROUNDS",(0,1), (-1,-1), [colors.white, LIGHT]),
                ("TOPPADDING",    (0,0), (-1,-1), 5),
                ("BOTTOMPADDING", (0,0), (-1,-1), 5),
                ("LEFTPADDING",   (0,0), (-1,-1), 6),
            ]
            for i, row in enumerate(action_rows, 1):
                bg = priority_colors.get(row[2], colors.white)
                at_style.append(("BACKGROUND", (2, i), (2, i), bg))
            at.setStyle(TableStyle(at_style))
            story.append(at)
            story.append(Spacer(1, 0.5*cm))

            # ── 10. Sign-off ─────────────────────────────────────
            hdr = Table(
                [[Paragraph("10. Sign-off", S("SHdr3", fontSize=12,
                             fontName="Helvetica-Bold", textColor=colors.white))]],
                colWidths=[W - 4*cm],
            )
            hdr.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,-1), BRAND),
                ("TOPPADDING",    (0,0), (-1,-1), 7),
                ("BOTTOMPADDING", (0,0), (-1,-1), 7),
                ("LEFTPADDING",   (0,0), (-1,-1), 10),
            ]))
            story.append(hdr)
            story.append(Spacer(1, 0.15*cm))

            so_data = [
                [Paragraph("<b>Role</b>", body), Paragraph("<b>Name</b>", body),
                 Paragraph("<b>Signature</b>", body), Paragraph("<b>Date</b>", body)],
                ["On-Call Engineer", "", "", ""],
                ["SRE Lead",         "", "", ""],
                ["Engineering Manager", "", "", ""],
            ]
            so = Table(so_data, colWidths=[4.5*cm, 4*cm, 4.5*cm, 2.5*cm])
            so.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,0), colors.HexColor("#f1f5f9")),
                ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
                ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
                ("ROWBACKGROUNDS",(0,1), (-1,-1), [colors.white, LIGHT]),
                ("TOPPADDING",    (0,0), (-1,-1), 8),
                ("BOTTOMPADDING", (0,0), (-1,-1), 8),
                ("LEFTPADDING",   (0,0), (-1,-1), 8),
                ("FONTSIZE",      (0,0), (-1,-1), 9),
            ]))
            story.append(so)
            story.append(Spacer(1, 0.8*cm))

            # ── Footer note ──────────────────────────────────────
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")))
            story.append(Spacer(1, 0.2*cm))
            story.append(Paragraph(
                f"This report was automatically generated by the <b>{self.company} AI RCA Agent</b> "
                f"powered by Ollama (offline AI). AI confidence: {rca.confidence_score:.0%}. "
                f"All findings must be reviewed by a qualified engineer before implementation.",
                small,
            ))
            story.append(Paragraph(
                f"Incident ID: {incident_id} &nbsp;·&nbsp; Generated: {ts_human}",
                small,
            ))

            doc = SimpleDocTemplate(
                str(path), pagesize=A4,
                rightMargin=2*cm, leftMargin=2*cm,
                topMargin=2*cm, bottomMargin=2*cm,
                title=f"RCA Report — {short_id}",
                author=self.company,
                subject=f"Root Cause Analysis — {namespace}",
            )
            doc.build(story)
            logger.info("PDF report written: %s", path)

        except Exception as exc:
            logger.error("PDF generation failed: %s", exc)
            path.with_suffix(".txt").write_text(
                f"PDF generation failed: {exc}\n\nRCA Summary:\n{rca.executive_summary}"
            )

        return path
